export const RestaurantName = [
    {
        name:".CN Chinese",
        rating:5,
        location:"📍228 City Road, Cardiff",
        code:"CF24 3JH",
        cuisine:"🍴Chinese",
    },
    {
        name:"@ Thai",
        rating:5,
        location:"📍 376 Rayleigh Road, Essex",
        code:"SS9 5PT",
        cuisine:"🍴Thai",
    },
    {
        name:"@ Thai Restaurant",
        rating:5,
        location:"📍30 Greyhound Road Hammersmith, London",
        code:"W6 8NX",
        cuisine:"🍴Thai",
    },
    {
        name:"Thai Restaurant",
        rating:5,
        location:"📍30 Greyhound Road Hammersmith, London",
        code:"W6 8NX",
        cuisine:"🍴Thai",
    },
    {
        name:"@Indian.com",
        rating:5,
        location:"📍 9 Broughton Hall Road, Broughton",
        code:"CH4 0QR",
        cuisine:"🍴Curry",
    },
    {
        name:"007 Takeaway",
        rating:5,
        location:"📍 6 Drummond Street, Rotherham",
        code:"S65 1HY",
        cuisine:"🍴Pizza",
    },
    {
        name: "042 Restaurant & Bar",
        rating:3,
        location:"📍 885 High Road Leytonstone, London",
        code:"E11 1HR",
        cuisine:"🍴African",
    },
    {
        name: "042 Restaurant & Bar",
        rating:3,
        location:"📍 885 High Road Leytonstone, London",
        code:"E11 1HR",
        cuisine:"🍴African",
    },
    {
        name: "042 Restaurant & Bar",
        rating:3,
        location:"📍 885 High Road Leytonstone, London",
        code:"E11 1HR",
        cuisine:"🍴African",
    },
    {
        name: "1 2 3 Chinese",
        rating:5,
        location:"📍Unit 4 Spencer House, Swalwell",
        code:"NE16 3DS",
        cuisine:"🍴Chinese",
    },
    {
        name: "1 2 3 Chinese",
        rating:5,
        location:"📍Unit 4 Spencer House, Swalwell",
        code:"NE16 3DS",
        cuisine:"🍴Chinese",
    },
    {
        name: "100 Degrees Chinese Restaurant",
        rating:5,
        location:"📍67 Park Street, Treforest",
        code:"CF37 1SN",
        cuisine:"🍴Chinese",
    },
    {
        name: "100 Menu",
        rating:5,
        location:"📍50 Wallgate, Wigan",
        code:"WN1 1JU",
        cuisine:"🍴Chinese",
    },{
        name: "104 Turkish BBQ",
        rating:5,
        location:"📍104 Tanners Lane, Essex",
        code:"IG6 1QE",
        cuisine:"🍴Turkish",
    },{
        name: "109 Ristorante",
        rating:5,
        location:"📍109 Westbourne Park Road, London",
        code:"W2 5QL",
        cuisine:"🍴Pizza",
    },
    {
        name: "113 Fish Bar",
        rating:5,
        location:"📍113 Poulton Road, Merseyside",
        code:"CH44 9DE",
        cuisine:"🍴Chinese",
    },
    {
        name: "1498 The Spice Affair",
        rating:5,
        location:"📍Red Lion Hotel, Spalding",
        code:"PE11 1SU",
        cuisine:"🍴Curry",
    },
    {
        name: "168 Chinese & Cantonese Takeaway",
        rating:5,
        location:"📍 17 Alexandra Road, West Yorkshire",
        code:"LS18 4HE",
        cuisine:"🍴Chinese",
    },
    {
        name: "1A Work",
        rating:4,
        location:"📍 Unit 2 30 Greenock Road, Bishopton",
        code:"PA7 5JN",
        cuisine:"🍴Chinese",
    },
    {
        name: "1pizza1",
        rating:4,
        location:"📍 160 Leeds Road, Leeds",
        code:"LS26 0JH",
        cuisine:"🍴Pizza",
    },
    {
        name: "1st Class Pizza",
        rating:4,
        location:"📍 1 Walsall Road, Cannock",
        code:"WS11 0HG",
        cuisine:"🍴Pizza",
    },
    {
        name: "1st Class Pizza",
        rating:5,
        location:"📍 388 Filton Avenue, Bristo",
        code:"WS11 0HG",
        cuisine:"🍴Pizza",
    },
    {
        name: "1st Class Pizza",
        rating:5,
        location:"📍 388 Filton Avenue, Bristo",
        code:"WS11 0HG",
        cuisine:"🍴Pizza",
    },
    {
        name: "1st Class Pizza",
        rating:5,
        location:"📍 70 Carter Lane, Mansfield",
        code:"WS11 0HG",
        cuisine:"🍴Pizza",
    },
]